name: Python Application

on:
  push:
    branches:
        - main
    
jobs:
    build-and-deploy:
        runs-on: self-hosted

        steps:
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: 3.10

            - name: Run main.py
              run: python main.py